org: ryanycw
app: mmc-quant
service: ${env:SERVERLESS_SERVICE_NAME}
frameworkVersion: "3"
useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ${env:AWS_REGION_MMC}
  profile: ${env:AWS_PROFILE_MMC} # profile of your aws credentials
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 29 # optional, in seconds, default is 6
  environment:
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - lambda:InvokeFunction
            - lambda:InvokeAsync
          Resource:
            - "arn:aws:dynamodb:${aws:region}:*:table/${env:AWS_DYNAMODB_TABLE_NAME}"

functions:
  - ${file(serverless/execOrder.yml)}

resources:
  - ${file(serverless/resource.yml)}